//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crawller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class terms_before_Stemming
    {
        public int id { get; set; }
        public string term { get; set; }
        public int doc_id { get; set; }
    
        public virtual page page { get; set; }
    }
}
